# Site settings
author: Dmitry Rogozhny
title: Dmitry Rogozhny
email: drogozhny@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: https://dmitryrogozhny.com
twitter_username: dro_stories
github_username:  dmitryrogozhny
linkedin_username: drogozhny
description: >
  Software Development described

google_analytics: UA-100633158-1
disqus:
  shortname: dmitryrogozhny

twitter:
  username: dro_stories

# Posts settings
permalink: /blog/:title
# paginate: 2

# Build settings
markdown: kramdown
theme: minima

# excerpt_separator: "<!--more-->"

sass:
    style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
